/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface __MFCallStack : NSObject
{
    void **_frames;
    unsigned int _count;
}

- (id)initWithFrames:(void **)arg1 count:(unsigned int)arg2;
- (void)dealloc;
- (void)finalize;
- (int)frameCount;
- (void **)frames;
- (id)copyArrayRepresentation;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;

@end

