/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class Message, NSString;

@interface _AppleScriptHeaderRecord : NSObject
{
    NSString *_name;
    id _content;
    Message *_message;
}

- (void)dealloc;
- (void)finalize;
- (id)name;
- (void)setName:(id)arg1;
- (id)content;
- (void)setContent:(id)arg1;
- (id)message;
- (void)setMessage:(id)arg1;
- (id)objectSpecifier;

@end

