/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class IMAPAccount, NSArray;

@interface _IMAPMailboxDeletionQueueEntry : NSObject
{
    NSArray *_urls;
    NSArray *_paths;
    IMAPAccount *_account;
}

- (void)dealloc;
@property(retain, nonatomic) IMAPAccount *account; // @synthesize account=_account;
@property(retain, nonatomic) NSArray *paths; // @synthesize paths=_paths;
@property(retain, nonatomic) NSArray *urls; // @synthesize urls=_urls;

@end

