/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "MessageConsumer-Protocol.h"

@class NSMutableArray;

@interface _MessageCollector : NSObject <MessageConsumer>
{
    NSMutableArray *_messages;
    int _accessNumber;
    BOOL _didCancel;
}

- (id)init;
- (void)dealloc;
- (id)messages;
- (void)newMessagesAvailable:(id)arg1 conversationsMembersByMessageID:(id)arg2;
- (void)newMessagesAvailable:(id)arg1 conversationMembers:(id)arg2;
- (BOOL)shouldCancel;
- (BOOL)didCancel;
- (void)finishedSendingMessages;

@end

