/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/_MFMessageSortingValueSender.h>

@interface _MFMessageSortingValueSenderOnline : _MFMessageSortingValueSender
{
    BOOL _senderIsAvailableOnline;
}

- (BOOL)senderIsAvailableOnline;
- (void)setSenderIsAvailableOnline:(BOOL)arg1;
- (id)description;

@end

