/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/MFMessageSortingValue.h>

@interface _MFMessageSortingValueUid : MFMessageSortingValue
{
    unsigned int _uidForSort;
}

- (unsigned int)uidForSort;
- (void)setUidForSort:(unsigned int)arg1;
- (id)description;

@end

