/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/MFMessageSortingValue.h>

@class NSArray;

@interface _MFMessageSortingValueTo : MFMessageSortingValue
{
    NSArray *_to;
}

- (void)dealloc;
- (id)to;
- (void)setTo:(id)arg1;
- (id)description;

@end

