/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/MFMessageSortingValue.h>

@interface _MFMessageSortingValueNumberOfAttachments : MFMessageSortingValue
{
    unsigned long long _numberOfAttachments;
}

- (unsigned long long)numberOfAttachments;
- (void)setNumberOfAttachments:(unsigned long long)arg1;
- (id)description;

@end

