/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/MFMessageSortingValue.h>

@class NSString;

@interface _MFMessageSortingValueSender : MFMessageSortingValue
{
    NSString *_senderAddressComment;
}

- (void)dealloc;
- (id)senderAddressComment;
- (void)setSenderAddressComment:(id)arg1;
- (id)description;

@end

