/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "ABRecord.h"

@interface ABRecord (MessageAdditions)
- (id)firstName;
- (id)lastName;
- (id)middleName;
- (id)nickname;
- (id)extension;
- (id)_fullName;
- (long long)fullNameCompare:(id)arg1;
- (id)email;
- (id)allEmailAddresses;
- (id)compoundName;
- (id)compoundNameAndEmail;
- (id)compoundNameAndEmailForEmail:(id)arg1;
- (BOOL)isGroup;
@end

