/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface AccountSetupValidatorAttempt : NSObject
{
    unsigned int _portNumber;
    long long _securityLayerType;
    BOOL _usesSSL;
}

+ (id)attemptsForAccount:(id)arg1 accountInfo:(id)arg2;
- (id)description;
@property long long securityLayerType; // @synthesize securityLayerType=_securityLayerType;
@property BOOL usesSSL; // @synthesize usesSSL=_usesSSL;
@property unsigned int portNumber; // @synthesize portNumber=_portNumber;

@end

