/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface AuthorTransporter : NSObject
{
    NSString *_name;
    NSString *_email;
}

- (id)initWithAuthor:(id)arg1;
- (void)dealloc;
@property(copy) NSString *email; // @synthesize email=_email;
@property(copy) NSString *name; // @synthesize name=_name;

@end

