/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "EWSPathToExtendedFieldType.h"

@interface EWSPathToExtendedFieldType (MessageAdditions)
+ (id)_newExtendedFieldTypeForPropertyTag:(id)arg1 propertyType:(int)arg2;
+ (id)newExtendedFieldTypeForPropertyTag:(id)arg1;
+ (id)newExtendedFieldTypeForPropertyId:(long long)arg1;
@end

