/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/RemoteStoreSizeEngine.h>

@interface EWSSizeEngine : RemoteStoreSizeEngine
{
}

- (id)initWithAccount:(id)arg1;
- (void)_runWorkerThread;
- (void)_getSizeForMailboxUid:(id)arg1;

@end

