/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/EWSUpdateItemRequestOperation.h>

@interface EWSUpdateItemSetFlagsRequestOperation : EWSUpdateItemRequestOperation
{
}

- (id)initWithEWSItemIds:(id)arg1 messageType:(BOOL)arg2 flags:(id)arg3 gateway:(id)arg4 errorHandler:(id)arg5;
- (id)awakeAfterUsingCoder:(id)arg1;

@end

