/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPAggregateClientOperation.h>

@interface IMAPAggregateFetchUIDOperation : IMAPAggregateClientOperation
{
    unsigned int _expectedSize;
}

- (id)initWithOperations:(id)arg1 expectedSize:(unsigned int)arg2;
- (id)commandTypeString;
- (void)cleanupAfterCompletion;
@property unsigned int expectedSize; // @synthesize expectedSize=_expectedSize;

@end

