/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPClientMailboxOperation.h>

@class NSString;

@interface IMAPClientRenameOperation : IMAPClientMailboxOperation
{
    NSString *_nameForNewMailbox;
    NSString *_nameForNewMailboxArgument;
}

- (id)initWithMailboxName:(id)arg1 newMailboxName:(id)arg2;
- (void)dealloc;
- (id)commandTypeString;
- (id)detailsString;
- (id)newCommandDataForLiteralPlus:(BOOL)arg1;
@property(copy) NSString *nameForNewMailboxArgument; // @synthesize nameForNewMailboxArgument=_nameForNewMailboxArgument;
@property(copy) NSString *nameForNewMailbox; // @synthesize nameForNewMailbox=_nameForNewMailbox;

@end

