/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPClientUIDOperation.h>

@interface IMAPClientUIDExpungeOperation : IMAPClientUIDOperation
{
}

- (id)initWithMailboxName:(id)arg1 UIDs:(id)arg2;
- (id)commandTypeString;
- (BOOL)executeOnConnection:(id)arg1;

@end

