/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPClientListOperation.h>

@interface IMAPClientLSubOperation : IMAPClientListOperation
{
}

- (id)initWithMailboxName:(id)arg1 referenceName:(id)arg2 options:(int)arg3;
- (id)commandTypeString;

@end

