/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPClientOperation.h>

@interface IMAPClientSuspendOperation : IMAPClientOperation
{
    BOOL _shouldExecuteSynchronously;
}

- (id)init;
- (id)commandTypeString;
@property BOOL shouldExecuteSynchronously; // @synthesize shouldExecuteSynchronously=_shouldExecuteSynchronously;

@end

