/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPSingleClientOperation.h>

@class NSString;

@interface IMAPClientGetQuotaOperation : IMAPSingleClientOperation
{
    NSString *_quotaRoot;
}

- (id)initWithQuotaRoot:(id)arg1;
- (void)dealloc;
- (id)commandTypeString;
- (id)newCommandDataForLiteralPlus:(BOOL)arg1;
@property(copy) NSString *quotaRoot; // @synthesize quotaRoot=_quotaRoot;

@end

