/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMapTable;

@interface MessageStringUniquer : NSObject
{
    NSMapTable *_stringsTable;
}

- (id)init;
- (id)copyUniquedStringForIndex:(long long)arg1;
- (void)setUniquedString:(id)arg1 forIndex:(long long)arg2;
- (id)description;
- (void)dealloc;

@end

