/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

//#import "NSObject.h"

@class Message;

@interface MessageBody : NSObject
{
    long long _messageID;
    Message *_message;
    BOOL _hideCalendarMimePart;
}

- (id)init;
- (void)dealloc;
- (id)message;
- (void)setMessage:(id)arg1;
- (id)attributedString;
- (BOOL)isHTML;
- (BOOL)isRich;
@property(readonly) BOOL isSignedByMe;
- (void)calculateNumberOfAttachmentsIfNeeded;
- (void)calculateNumberOfAttachmentsDecodeIfNeeded;
- (unsigned int)numberOfAttachmentsSigned:(char *)arg1 encrypted:(char *)arg2 numberOfTNEFAttachments:(unsigned int *)arg3;
- (id)attachmentsWithContext:(id)arg1;
- (id)attachments;
- (id)attachmentViewControllers;
- (id)attachmentFilenames;
- (id)textHtmlPart;
- (id)webArchive;
@property BOOL hideCalendarMimePart; // @synthesize hideCalendarMimePart=_hideCalendarMimePart;
@property long long messageID; // @synthesize messageID=_messageID;
- (void)renderString:(id)arg1;

@end

