/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

//#import "NSObject-Protocol.h"

@protocol MFChanging <NSObject>
- (void)beginChanging;
- (BOOL)endChanging:(BOOL)arg1;
- (BOOL)endChanging:(BOOL)arg1 immediately:(BOOL)arg2;
@end

