/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

//#import "NSObject.h"

@interface MFHTMLParser : NSObject
{
}

+ (id)plainTextFromHTML:(id)arg1 limit:(unsigned long long)arg2;
+ (id)plainTextFromHTML:(id)arg1;
+ (id)plainTextFromHTMLSnippet:(id)arg1;

@end

