/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface MFLibraryIDWrapper : NSObject
{
}

+ (void *)createLibraryIDWrapper:(long long)arg1;
+ (void)releaseLibraryIDWrapper:(void *)arg1;
+ (long long)libraryIDFromWrapper:(void *)arg1;
+ (id)createNumberFromWrapper:(void *)arg1;

@end

