/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

//#import "NSObject.h"

@interface MFMimeDecodeContext : NSObject
{
    BOOL _decodeTextPartsOnly;
    BOOL _shouldSkipUpdatingMessageFlags;
}

@property(nonatomic) BOOL shouldSkipUpdatingMessageFlags; // @synthesize shouldSkipUpdatingMessageFlags=_shouldSkipUpdatingMessageFlags;
@property(nonatomic) BOOL decodeTextPartsOnly; // @synthesize decodeTextPartsOnly=_decodeTextPartsOnly;

@end

