/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface MFQuoteParser : NSObject
{
    NSString *_quoteBlockHtmlPrefix;
    NSString *_quoteBlockHtmlSuffix;
}

- (id)initWithHtmlQuoteBlockHtmlPrefix:(id)arg1 quoteBlockHtmlSuffix:(id)arg2;
- (void)dealloc;
- (id)finalHtmlContentWithBlockQuoteChangesIfNeededForHtml:(struct __CFString *)arg1 startIndex:(unsigned long long)arg2 quoteProcessingStyle:(long long)arg3 allowMultipleQuoteBlocks:(BOOL)arg4;
- (id)strippedQuoteBlockWithHtml:(id)arg1;
- (id)escapedQuoteBlockWithHtml:(id)arg1;
- (void)reset;

@end

