/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol MFUIMailbox <NSObject>
- (id)persistentIdentifier;
- (id)displayName;
- (id)extendedDisplayName;
- (BOOL)isContainer;
- (unsigned long long)displayCount;
- (long long)numberOfChildren;
- (BOOL)hasChildren;
- (id)children;
- (BOOL)isStore;
- (BOOL)isSmartMailbox;
- (id)account;
- (id)accountURLString;
- (BOOL)isPlaceholder;
- (BOOL)isDescendantOfMailboxWithType:(int)arg1;
@property int type;
@end

