/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSArray.h"

@interface NSArray (EmailAddressArray)
- (id)uncommentedAddressList;
- (id)addressString;
- (id)addressCommentString;
- (id)addressDisplayStringWithMaxNumberOfAddresses:(unsigned long long)arg1;
@end

