/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSAttributedString.h"

@interface NSAttributedString (find_attribute)
- (id)nextAttribute:(id)arg1 fromLocation:(unsigned long long)arg2 effectiveRange:(struct _NSRange *)arg3;
@end

