/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSAttributedString.h"

@interface NSAttributedString (FormatFlowedSupport)
- (void)getFormatFlowedString:(id *)arg1 insertedTrailingSpaces:(char *)arg2 encoding:(unsigned int)arg3;
- (void)getQuotedString:(id *)arg1 encoding:(unsigned int)arg2;
@end

