/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSDate.h"

@interface NSDate (Goodies)
+ (id)newDateInCommonFormatsWithString:(id)arg1;
+ (id)lenientDateInCommonFormatsWithString:(id)arg1;
- (id)descriptionInBSDMailboxFormat;
- (id)replyPrefixForSender:(id)arg1 withSpacer:(BOOL)arg2;
@end

