/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

//#import "NSFileWrapper.h"

@interface NSFileWrapper (HFSDataConversion)
- (id)appleSingleDataWithFilename:(const char *)arg1 length:(unsigned long long)arg2;
- (id)appleDoubleDataWithFilename:(const char *)arg1 length:(unsigned long long)arg2;
@end

