/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface SafeValueCache : NSObject
{
    id _value;
    long long _state;
    id _target;
    SEL _selector;
}

- (id)initWithUpdateTarget:(id)arg1 selector:(SEL)arg2;
- (void)dealloc;
- (void)clearTarget;
@property(retain) id value;
- (id)retainedValue;
- (void)invalidate;

@end

