/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSConditionLock, NSMutableArray, NSMutableDictionary, NSMutableSet, _NonContentSmartMailboxUnreadCountManager;

@interface SmartMailboxUnreadCountManager : NSObject
{
    NSMutableArray *_smartMailboxes;
    NSMutableDictionary *_smartMailboxesOpenDates;
    BOOL _updateNeededAfterOpeningMailboxes;
    NSMutableDictionary *_unreadMessagesBySmartMailbox;
    NSMutableDictionary *_smartMailboxesUpdates;
    NSConditionLock *_watchedMessagesLock;
    NSMutableDictionary *_watchedMessages;
    NSMutableDictionary *_messagesNeedingToBeIndexed;
    NSConditionLock *_isUpdatingStateLock;
    NSConditionLock *_isDirtyStateLock;
    double _lastModificationToUpdate;
    NSConditionLock *_obsoleteMessageKeysLock;
    NSMutableSet *_obsoleteMessageKeys;
    _NonContentSmartMailboxUnreadCountManager *_nonContentSmartMailboxUnreadCountManager;
}

+ (void)initialize;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
- (id)init;
- (id)retain;
- (unsigned long long)retainCount;
- (void)release;
- (id)autorelease;
- (void)setSmartMailboxes:(id)arg1;
- (void)smartMailbox:(id)arg1 didInitializeWithDictionaryRepresentation:(id)arg2;
- (void)smartMailbox:(id)arg1 willReturnDictionaryRepresentation:(id)arg2;
- (void)_setIsUpdating:(BOOL)arg1;
- (void)_setIsDirty:(BOOL)arg1;
- (id)_keyForMailbox:(id)arg1;
- (id)_keyForMessage:(id)arg1;
- (void)_decomposeMessageKey:(id)arg1 intoRowID:(id *)arg2 messageIDHeader:(id *)arg3;
- (id)_pathForMessage:(id)arg1;
- (void)_setSmartMailboxesWithBodyCriterion:(id)arg1;
- (BOOL)_isObservingSmartMailbox:(id)arg1;
- (void)_startObservingNotifications;
- (void)_stopObservingNotifications;
- (void)_messagesAdded:(id)arg1;
- (void)_messageFlagsChanged:(id)arg1;
- (void)_messagesCompacted:(id)arg1;
- (void)_mailboxesDeleted:(id)arg1;
- (void)_storeWillOpen:(id)arg1;
- (void)_storeDidOpen:(id)arg1;
- (void)_smartMailboxesWillSaveToDisk:(id)arg1;
- (void)_smartMailboxesDidSaveToDisk:(id)arg1;
- (void)_setUnreadMessages:(id)arg1 forSmartMailbox:(id)arg2 onDate:(id)arg3;
- (unsigned long long)_uniqueCountOfMessages:(id)arg1;
- (void)_watchMessages:(id)arg1 withUnreadState:(BOOL)arg2 onDate:(id)arg3;
- (void)_performDelayedUpdate:(id)arg1;
- (void)_performUpdateNow;
- (void)_updateUnreadCountsWithWatchedMessages;
- (id)_filterMessages:(id)arg1 matchingCriterion:(id)arg2;
- (void)_updateSmartMailboxUnreadCountsWithMessages:(id)arg1;
- (void)_updateSmartMailboxUnreadCountsByRemovingMessagesWithKeys:(id)arg1;
- (void)_addMessagesWaitingToBeIndexed:(id)arg1;
- (BOOL)_isMessageIndexed:(id)arg1;
- (id)_messageKeysWaitingToBeIndexes;
- (void)_addObsoleteMessageKeys:(id)arg1;
- (void)_updateObsoleteMessageKeys;
@property double lastModificationToUpdate; // @synthesize lastModificationToUpdate=_lastModificationToUpdate;

@end

