/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSManagedObject.h"

@interface TransientBookmarkItem : NSManagedObject
{
}

+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
+ (void)setEntity:(id)arg1;
+ (id)entity;
- (id)name;
- (void)setName:(id)arg1;
- (void)setPosition:(id)arg1;
- (id)parent;
- (void)setParent:(id)arg1;
- (void)setParent:(id)arg1 updatingContainsFeed:(BOOL)arg2;

@end

